# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: c02375545213063d66f1f8e28469b55486d01a107363cb2ee42d5b9cb134e3d268575ac239cec37ee4360e2cf85019c86de3d444fc6dba73b092c9267fa8b9b3

test:
  secret_key_base: 05bab2465bfea2073fcaf07b098449b3d0d5bb8e90fe071463974821235eca9ae9df8475120ae3419d97163b4e9ce37e582768c565e7b50b25b17fbe966ac4d1

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
